copy global.js +^
    browser.js +^
    class.js +^
    user.js +^
    oauth.js +^
    polyfill.js +^
    util.js +^
    event.js +^
    random.js +^
    cookies.js +^
    ajax.js +^
    webserviceurl.js +^
    webservice.js +^
    list.js +^
    canvas.js +^
    matrix.js +^
    drawable.js +^
    timer.js +^
    composite.js +^
    loader.js +^
    image.js +^
    sprite.js +^
    button.js +^
    panel.js +^
    label.js +^
    font.js +^
    textbutton.js +^
    spritebutton.js +^
    menu.js +^
    window.js +^
    messagebox.js +^
    keyboard.js +^
    mouse.js +^
    debug.js +^
    desktop.js +^
    startup.js ^
 glib_min.js
