set CURDIR=%CD%
WinSCP /command "open FatCow" "synchronize remote ""%CURDIR%\public_html"" /skilbeck/mtw" "exit"
WinSCP /command "open DigitalOcean" "synchronize remote ""%CURDIR%\SQL"" /home/chs/sql" "exit"
WinSCP /command "open DigitalOcean" "synchronize remote ""%CURDIR%\web_service"" /usr/local/www/debug/" "exit"
WinSCP /command "open DigitalOcean" "synchronize remote ""%CURDIR%\nodejs"" /home/chs/nodejs" "exit"
WinSCP /command "open DigitalOcean" "synchronize remote ""%CURDIR%\public_html\js"" /home/chs/nodejs/js"  "exit"
WinSCP /command "open DigitalOcean" "synchronize remote ""%CURDIR%\manager"" /home/chs/manager"  "exit"
WinSCP /command "open DigitalOcean" "synchronize remote ""%CURDIR%\config"" /usr/local/www/debug"  "exit"

start /b WinSCP /command "open FatCow" "keepuptodate ""%CURDIR%\public_html"" /skilbeck/mtw"
start /b WinSCP /command "open Debian" "keepuptodate ""%CURDIR%\SQL"" /home/chs/sql"
start /b WinSCP /command "open Debian" "keepuptodate ""%CURDIR%\web_service"" /usr/local/www/debug"
start /b WinSCP /command "open Debian" "keepuptodate ""%CURDIR%\nodejs"" /home/chs/nodejs"
start /b WinSCP /command "open Debian" "keepuptodate ""%CURDIR%\public_html\js"" /home/chs/nodejs/js"
start /b WinSCP /command "open Debian" "keepuptodate ""%CURDIR%\manager"" /home/chs/manager"
